### ISSUE TITLE
Attribute error running it in V3.4.2

### ISSUE THREAD

**Issue by Jujonet** [bilbaomakers/PVPC-ESIOS#1]
Hello
Have difficulties running it under v3.4.2 (ARMBIAN 5.38 stable Ubuntu 16.04.4 LTS 4.14.18-sunxi)

Get the following when running python3 pvpc.py

```
Traceback (most recent call last):
  File "pvpc.py", line 59, in <module>
    t_valor_date = datetime.fromisoformat(t_valor['datetime'])
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

Tried to import directly the datetime directly (import datetime) with no success.

Any idea?

Thank you

**Comment by agustinscaz** [comment]
You are using an older version of python. You must use version >3.7
